spring:
  servlet:
    multipart:
      max-request-size: 3MB
      max-file-size: 3MB
  datasource:
    url: jdbc:mysql://mysql:3306/tek_chin?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Use 'validate' to ensure the schema matches without altering it
    show-sql: false  # SQL logging should be off for production
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    whiteListUrls:
      - /api/v1/carousel/query
      - /api/v1/post/query
      - /api/v1/auth/**
      - /v2/api-docs
      - /v3/api-docs
      - /v3/api-docs/**
      - /swagger-resources
      - /swagger-resources/**
      - /configuration/ui
      - /configuration/security
      - /swagger-ui/**
      - /webjars/**
      - /swagger-ui.html
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
