server:
  port: 8443  # Port for HTTPS
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: qpal9865
    key-alias: tomcat

spring:
  servlet:
    multipart:
      max-request-size: 3MB
      max-file-size: 3MB
  datasource:
    url: jdbc:mysql://pub-tek-0908.cho60u6i0b7g.ap-northeast-1.rds.amazonaws.com/tek_chin?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Use 'validate' to ensure the schema matches without altering it
    show-sql: false  # SQL logging should be off for production
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    whiteListUrls:
      /api/v1/carousel/query,
      /api/v1/post/query,
      /api/v1/auth/**,
      /v2/api-docs,
      /v3/api-docs,
      /v3/api-docs/**,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui/**,
      /webjars/**,
      /swagger-ui.html,
      /,
      /News,
      /About,
      /Contact,
      /Login,
      /admin/**,
      /_nuxt/**,
      /login,
      /favicon.ico,
      /car.ico
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
